name: Brush steps

on:
  schedule:
    - cron: '25 2,5,8,11 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout codes
        uses: actions/checkout@v4.1.1
      - name: Update system and install zsh
        run: |
          sudo -E apt-get -qq update
          sudo -E apt-get install zsh -y
      - name: Initializing Python
        uses: actions/setup-python@v5.0.0
        with:
          python-version: 3.8
      - name: Start
        env:
            CONFIG: ${{ secrets.CONFIG }}
        run: |
          pip3 install requests pytz
          python3 main.py
